# Generated by Django 5.2.16 on 2026-07-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement_accounts', '0002_account_entreprise'),
        ('recrutement_jobs', '0004_application_extracted_cv_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Pourcentage de compatibilité (0 à 100)')),
                ('cv_path', models.CharField(help_text='Chemin ou nom du fichier CV physique', max_length=500)),
                ('competence_candidat', models.JSONField(help_text='Dictionnaire des compétences trouvées classées par catégories')),
                ('forces', models.JSONField(default=list, help_text='Liste des compétences requises trouvées')),
                ('manques', models.JSONField(default=list, help_text='Liste des compétences requises manquantes')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, help_text="Date à laquelle l'analyse a été effectuée")),
                ('application', models.OneToOneField(blank=True, help_text='La candidature complète liée (optionnel mais recommandé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyse_cv', to='recrutement_jobs.application')),
                ('candidat', models.ForeignKey(help_text='Le candidat lié à ce CV', on_delete=django.db.models.deletion.CASCADE, related_name='analyses_cv', to='recrutement_accounts.candidate')),
                ('job', models.ForeignKey(help_text="L'offre d'emploi pour laquelle le CV est analysé", on_delete=django.db.models.deletion.CASCADE, related_name='analyses_cv', to='recrutement_jobs.joboffer')),
            ],
        ),
    ]
