# Generated by Django 5.2.16 on 2026-07-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(help_text="Copie historique du type d'offre", max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_start_date_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active')], default='draft', max_length=50)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='recrutement_jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifié', 'Planifié'), ('effectué', 'Effectué'), ('annulé', 'Annulé')], default='planifié', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recrutement_jobs.application')),
            ],
        ),
    ]
