# Generated by Django 5.2.16 on 2026-07-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement_interviews', '0001_initial'),
        ('recrutement_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='recrutement_jobs.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recrutement_jobs.application'),
        ),
    ]
