# Generated by Django 5.2.16 on 2026-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_interviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('en_ligne', 'En ligne (Visio)'), ('presentiel', 'Présentiel'), ('telephone', 'Téléphone')], default='en_ligne', max_length=50),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, help_text='Lien Visio ou Adresse physique', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(default='Entretien', max_length=100),
        ),
    ]
