# Generated by Django 5.2.16 on 2026-07-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0002_account_entreprise'),
        ('recrutement_interviews', '0003_interview_interview_type_interview_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Lien direct vers le candidat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='recrutement_accounts.candidate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Durée en mois (pour CDD ou Stage)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin (pour CDD ou Stage)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_title',
            field=models.CharField(blank=True, help_text='Titre du poste (historisé)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salaire brut mensuel/annuel', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('alternance', 'Alternance')], default='cdi', help_text="Type de contrat (issu de l'offre)", max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_signature', 'En attente de signature'), ('active', 'Actif')], default='draft', max_length=50),
        ),
    ]
