# Generated by Django 5.2.16 on 2026-07-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(help_text='stage, cdi, cdd, alternance', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('recruteur', models.ForeignKey(help_text='Référence au recruteur', on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='recrutement_accounts.account')),
                ('offer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to='recrutement_jobs.offertype')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('postulé', 'Postulé'), ('validé_recruteur', 'Validé Recruteur'), ('refusé', 'Refusé')], default='postulé', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recrutement_accounts.candidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recrutement_jobs.joboffer')),
            ],
        ),
    ]
