# Generated by Django 5.2.16 on 2026-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='entreprise',
            field=models.CharField(blank=True, help_text="Entreprise proposant l'offre", max_length=100, null=True),
        ),
    ]
