# Generated by Django 5.2.16 on 2026-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_jobs', '0002_joboffer_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Lettre de motivation', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV', null=True, upload_to='cvs/'),
        ),
    ]
