# Generated by Django 5.2.16 on 2026-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_jobs', '0003_application_cover_letter_application_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extracted_cv_text',
            field=models.TextField(blank=True, help_text='Texte extrait automatiquement du CV', null=True),
        ),
    ]
