# Generated by Django 5.2.16 on 2026-07-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_jobs', '0004_application_extracted_cv_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='ex: JS, JAVA', max_length=100)),
                ('note', models.PositiveIntegerField(help_text='ex: 10, 20. Le total pour une offre ne doit pas dépasser 100')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_requises', to='recrutement_jobs.joboffer')),
            ],
        ),
    ]
