# Generated by Django 5.2.16 on 2026-08-03 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutement_accounts', '0008_alter_leaverequest_type_conge_delete_leavetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_entree', models.TimeField(default='08:00', help_text="Heure officielle d'entrée")),
                ('heure_sortie', models.TimeField(default='17:00', help_text='Heure officielle de sortie')),
                ('debut_pause_midi', models.TimeField(default='12:00', help_text='Début de la pause déjeuner')),
                ('fin_pause_midi', models.TimeField(default='13:00', help_text='Fin de la pause déjeuner')),
                ('penalite_retard_par_heure', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant déduit par heure de retard', max_digits=10)),
                ('taux_journalier_absence', models.DecimalField(decimal_places=2, default=0.0, help_text="Montant déduit par jour d'absence (sans solde)", max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Configurations Entreprise',
            },
        ),
        migrations.CreateModel(
            name='PointageEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('retard_minutes', models.IntegerField(default=0, help_text='Retard calculé en minutes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='recrutement_accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prime_fixe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prime_variable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_absences', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_retards', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='recrutement_accounts.employee')),
            ],
            options={
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
