# Generated by Django 5.2.16 on 2026-07-31 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0002_account_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(help_text='admin, recruteur, candidat,employé,manager', max_length=50),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='recrutement_accounts.account')),
                ('manager', models.ForeignKey(blank=True, help_text='Le manager qui encadre cet employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='recrutement_accounts.employee')),
            ],
        ),
    ]
