# Generated by Django 5.2.16 on 2026-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0003_alter_accounttype_name_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('recruteur', 'Recruteur'), ('candidat', 'Candidat'), ('employé', 'Employé'), ('manager', 'Manager')], help_text='Sélectionnez le type de compte', max_length=50),
        ),
    ]
