# Generated by Django 5.2.16 on 2026-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0004_alter_accounttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(help_text='admin, recruteur, candidat,employé,manager', max_length=50),
        ),
    ]
