# Generated by Django 5.2.16 on 2026-08-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0006_alter_accounttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du type de congé (ex: Congé payé, Maladie)', max_length=100)),
                ('deductible', models.BooleanField(default=True, help_text="Ce congé déduit-il le solde de l'employé ?")),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='solde_conges',
            field=models.FloatField(default=30.0, help_text='Solde de congés (en jours)'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='recrutement_accounts.employee')),
                ('type_conge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recrutement_accounts.leavetype')),
            ],
        ),
    ]
