# Generated by Django 5.2.16 on 2026-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement_accounts', '0007_leavetype_employee_solde_conges_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='type_conge',
            field=models.CharField(choices=[('conge_paye', 'Congé payé'), ('maladie', 'Maladie'), ('maternite', 'Maternité'), ('paternite', 'Paternité'), ('sans_solde', 'Sans solde'), ('autre', 'Autre')], default='conge_paye', max_length=50),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
